import {
  SiThreedotjs,
  SiReact,
  SiTailwindcss,
  SiVite,
  SiBlender,
  SiMongodb,
  SiExpress,
  SiNodedotjs,
  SiKotlin,
  SiMysql,
  SiAndroidstudio,
  SiUnity,
  SiReactrouter,
  SiMui,
  SiArduino,
  SiHtml5,
  SiCss3,
  SiJss,
  SiDocker,
  SiPytorch,
  SiPython,
  SiNumpy,
  SiScikitlearn,
} from "react-icons/si";

export const projects = [
  {
    title: "ArcFace Backbones",
    can: "images/projects/ArcfaceBackbones/ArcfaceCan.webp",
    images: [
      { src: "images/projects/ArcfaceBackbones/1.webp", alt: "Image1" },
      { src: "images/projects/ArcfaceBackbones/2.webp", alt: "Image2" },
      { src: "images/projects/ArcfaceBackbones/3.webp", alt: "Image3" },
      { src: "images/projects/ArcfaceBackbones/4.webp", alt: "Image4" },
    ],
    description: {
      en: "ArcFace Backbone Comparative is a PyTorch-based research project for evaluating lightweight face recognition backbones using a unified ArcFace pipeline. It simplifies the original InsightFace framework into a single-GPU, PyTorch-only setup, enabling efficient comparison of multiple architectures.",
      de: "ArcFace Backbone Comparative ist ein PyTorch-Forschungsprojekt zur Bewertung leichtgewichtiger Gesichtserkennungs-Backbones mit einer einheitlichen ArcFace-Pipeline. Es vereinfacht das ursprüngliche InsightFace-Framework auf ein Single-GPU-Setup und ermöglicht den effizienten Vergleich mehrerer Architekturen.",
    },
    tech: [SiPytorch, SiPython, SiNumpy, SiScikitlearn],
    features: {
      en: [
        "Unified ArcFace pipeline with single-GPU and FP16 support.",
        "Comparison of lightweight backbones like iResNet, MobileFaceNet, and ShuffleFaceNet.",
        "Modular and configurable training system.",
        "Multi-model evaluation with ROC and AUC metrics.",
        "Model complexity analysis (FLOPs and parameters).",
      ],
      de: [
        "Einheitliche ArcFace-Pipeline mit Single-GPU- und FP16-Unterstützung.",
        "Vergleich leichtgewichtiger Backbones wie iResNet, MobileFaceNet und ShuffleFaceNet.",
        "Modulares und konfigurierbares Trainingssystem.",
        "Multi-Modell-Evaluierung mit ROC- und AUC-Metriken.",
        "Modellkomplexitätsanalyse (FLOPs und Parameter).",
      ],
    },
    date: { en: "2026", de: "2026" },
    github: "https://github.com/ItO210/arcface-backbone-comparative",
  },

  {
    title: "3D Portfolio",
    can: "images/projects/3dPortfolio/3dPortfolioCan.webp",
    images: [
      { src: "images/projects/3dPortfolio/1.gif", alt: "Image1" },
      { src: "images/projects/3dPortfolio/2.gif", alt: "Image2" },
      { src: "images/projects/3dPortfolio/3.gif", alt: "Image3" },
      { src: "images/projects/3dPortfolio/4.gif", alt: "Image4" },
    ],
    description: {
      en: "3DPortfolio is an interactive personal portfolio built with Three.js and React Three Fiber. It presents a 3D environment with animated objects that represent sections like About Me, Contact, Music, Games, and Projects. HTML content is rendered directly on 3D model screens, enhanced with GSAP animations and multilingual support.",
      de: "3DPortfolio ist ein interaktives persönliches Portfolio, das mit Three.js und React Three Fiber erstellt wurde. Es präsentiert eine 3D-Umgebung mit animierten Objekten, die Bereiche wie Über mich, Kontakt, Musik, Spiele und Projekte darstellen. HTML-Inhalte werden direkt auf 3D-Modellbildschirmen gerendert, ergänzt durch GSAP-Animationen und Mehrsprachigkeit.",
    },
    tech: [SiThreedotjs, SiReact, SiTailwindcss, SiVite, SiBlender],
    features: {
      en: [
        "Immersive 3D navigation with interactive portfolio sections.",
        "HTML content embedded on 3D model surfaces.",
        "Dynamic hover effects and object interactions.",
        "Smooth GSAP-powered camera transitions.",
        "Multilanguage project descriptions.",
      ],
      de: [
        "Immersive 3D-Navigation mit interaktiven Portfolio-Bereichen.",
        "HTML-Inhalte direkt auf 3D-Modelloberflächen eingebettet.",
        "Dynamische Hover-Effekte und Objektinteraktionen.",
        "Sanfte GSAP-gesteuerte Kameraübergänge.",
        "Mehrsprachige Projektbeschreibungen.",
      ],
    },
    date: { en: "August 2025", de: "August 2025" },
    github: "https://github.com/sujitdaniel/Portfolio",
  },

  {
    title: "Cicata Nexus",
    can: "images/projects/CicataNexus/CicataNexusCan.webp",
    images: [
      { src: "images/projects/CicataNexus/1.webp", alt: "Image1" },
      { src: "images/projects/CicataNexus/2.webp", alt: "Image2" },
      { src: "images/projects/CicataNexus/3.webp", alt: "Image3" },
      { src: "images/projects/CicataNexus/4.webp", alt: "Image4" },
      { src: "images/projects/CicataNexus/5.webp", alt: "Image5" },
      { src: "images/projects/CicataNexus/6.webp", alt: "Image6" },
      { src: "images/projects/CicataNexus/7.webp", alt: "Image7" },
      { src: "images/projects/CicataNexus/8.webp", alt: "Image8" },
      { src: "images/projects/CicataNexus/9.webp", alt: "Image9" },
    ],
    description: {
      en: "Cicata Nexus is a web-based service request platform that centralizes equipment, materials, and support requests. It features role-specific dashboards, scheduling tools, and inventory tracking to streamline laboratory operations.",
      de: "Cicata Nexus ist eine webbasierte Serviceanfragen-Plattform, die Geräte-, Material- und Supportanfragen zentralisiert. Sie umfasst rollenspezifische Dashboards, Planungstools und Bestandsverfolgung zur Optimierung von Laborabläufen.",
    },
    tech: [
      SiReact,
      SiTailwindcss,
      SiVite,
      SiMongodb,
      SiExpress,
      SiNodedotjs,
      SiDocker,
    ],
    madeFor: [
      "CICATA Unidad Morelos",
      "https://mx.linkedin.com/company/cicatamor",
    ],
    features: {
      en: [
        "Centralized requests for equipment, materials, and support.",
        "Role-specific dashboards for users, managers, and admins.",
        "Integrated scheduling and calendar views.",
        "Inventory tracking and request history.",
        "Responsive design for desktop and mobile access.",
      ],
      de: [
        "Zentralisierte Anfragen für Geräte, Materialien und Support.",
        "Rollenspezifische Dashboards für Nutzer, Manager und Admins.",
        "Integrierte Planung und Kalenderansichten.",
        "Bestandsverfolgung und Anfragenverlauf.",
        "Responsives Design für Desktop und Mobile.",
      ],
    },
    date: { en: "August 2025", de: "August 2025" },
    github: "https://github.com/ItO210/service-request-manager",
  },

  {
    title: "Health Sync",
    can: "images/projects/HealthSync/HealthSyncCan.webp",
    images: [
      { src: "images/projects/HealthSync/1.webp", alt: "Image1" },
      { src: "images/projects/HealthSync/2.webp", alt: "Image2" },
      { src: "images/projects/HealthSync/3.webp", alt: "Image3" },
      { src: "images/projects/HealthSync/4.webp", alt: "Image4" },
      { src: "images/projects/HealthSync/5.webp", alt: "Image5" },
    ],
    madeFor: ["Hospital del Niño Morelense", "https://www.hnm.org.mx/"],
    description: {
      en: "HealthSync is a hospital equipment ticket management system for web and Android. Staff can report equipment issues online, while technicians and admins handle tickets through the mobile app. It supports repair tracking, evidence uploads, performance monitoring, and account management.",
      de: "HealthSync ist ein Ticket-Management-System für Krankenhausgeräte für Web und Android. Personal kann Geräteprobleme online melden, während Techniker und Admins Tickets über die App verwalten. Es unterstützt Reparaturverfolgung, Beweismittel-Uploads, Leistungsüberwachung und Kontoverwaltung.",
    },
    tech: [
      SiReact,
      SiTailwindcss,
      SiVite,
      SiKotlin,
      SiMysql,
      SiAndroidstudio,
      SiExpress,
      SiNodedotjs,
    ],
    features: {
      en: [
        "Web form for reporting equipment issues.",
        "Android app for technicians and admins.",
        "Ticket states for progress tracking.",
        "Evidence upload requirement for certain tickets.",
        "Performance stats and account management tools.",
      ],
      de: [
        "Webformular zur Meldung von Geräteproblemen.",
        "Android-App für Techniker und Admins.",
        "Ticket-Status zur Fortschrittsverfolgung.",
        "Pflicht zum Hochladen von Beweismitteln bei bestimmten Tickets.",
        "Leistungsstatistiken und Kontoverwaltungstools.",
      ],
    },
    date: { en: "September 2024", de: "September 2024" },
    github: "https://github.com/ItO210/equipment-ticket-system",
  },

  {
    title: "AI Racing Line",
    can: "images/projects/AIRacingLine/AIRacingLineCan.webp",
    images: [
      { src: "images/projects/AIRacingLine/1.webp", alt: "Image1" },
      { src: "images/projects/AIRacingLine/2.webp", alt: "Image2" },
      { src: "images/projects/AIRacingLine/3.webp", alt: "Image3" },
      { src: "images/projects/AIRacingLine/4.webp", alt: "Image4" },
    ],
    description: {
      en: "AIRacingLine is an AI-powered Unity tool that generates optimal racing lines and gives speed feedback in real time. An ML-Agents-trained AI drives the ideal path, which is recorded and shown with dynamic colors to guide acceleration and braking.",
      de: "AIRacingLine ist ein KI-gestütztes Unity-Tool, das optimale Rennlinien generiert und Echtzeit-Geschwindigkeitsfeedback gibt. Eine mit ML-Agents trainierte KI fährt den idealen Weg, der aufgezeichnet und mit dynamischen Farben zur Führung bei Beschleunigung und Bremsung angezeigt wird.",
    },
    madeFor: ["Rewind Games", "https://rewindgames.ca/"],
    tech: [SiUnity, SiUnity, SiUnity, SiUnity, SiUnity],
    features: {
      en: [
        "Trains AI agents with reward shaping and sensor tuning.",
        "Generates racing lines from AI driving data.",
        "Real-time color feedback for speed zones.",
        "Integration with Unity ML-Agents.",
        "Visual guidance for acceleration and braking.",
      ],
      de: [
        "Trainiert KI-Agenten mit Reward-Shaping und Sensor-Tuning.",
        "Generiert Rennlinien aus KI-Fahrdaten.",
        "Echtzeit-Farbfeedback für Geschwindigkeitszonen.",
        "Integration mit Unity ML-Agents.",
        "Visuelle Führung für Beschleunigung und Bremsung.",
      ],
    },
    date: { en: "September 2024", de: "September 2024" },
    github: "https://github.com/ItO210/ai-racing-line",
  },

  {
    title: "Code Cuisine",
    can: "images/projects/CodeCuisine/CodeCuisineCan.webp",
    images: [
      { src: "images/projects/CodeCuisine/2.webp", alt: "Image2" },
      { src: "images/projects/CodeCuisine/1.gif", alt: "Image1" },
      { src: "images/projects/CodeCuisine/3.webp", alt: "Image3" },
      { src: "images/projects/CodeCuisine/4.webp", alt: "Image4" },
      { src: "images/projects/CodeCuisine/5.webp", alt: "Image5" },
      { src: "images/projects/CodeCuisine/6.webp", alt: "Image6" },
    ],
    madeFor: ["Aulify", "https://www.aulify.mx/"],
    description: {
      en: "CodeCuisine is an educational game that teaches programming through a hamburger-making challenge. Players use drag-and-drop logic blocks to build recipes, and the system checks their logic with instant feedback. It includes progress tracking and an admin dashboard.",
      de: "CodeCuisine ist ein Lernspiel, das Programmierung durch eine Burger-Herausforderung lehrt. Spieler verwenden Drag-and-Drop-Logikblöcke zum Erstellen von Rezepten, und das System prüft ihre Logik sofort. Es umfasst Fortschrittsverfolgung und ein Admin-Dashboard.",
    },
    tech: [
      SiReact,
      SiTailwindcss,
      SiVite,
      SiMysql,
      SiExpress,
      SiNodedotjs,
      SiReactrouter,
      SiUnity,
      SiMui,
    ],
    features: {
      en: [
        "Teaches programming basics through play.",
        "Drag-and-drop logic block interface.",
        "Instant feedback on recipe logic.",
        "Tracks user progress and rankings.",
        "Admin dashboard for monitoring activity.",
      ],
      de: [
        "Vermittelt Programmierkenntnisse spielerisch.",
        "Drag-and-Drop-Logikblock-Oberfläche.",
        "Sofortiges Feedback zur Rezeptlogik.",
        "Verfolgt Fortschritt und Ranglisten.",
        "Admin-Dashboard zur Aktivitätsüberwachung.",
      ],
    },
    date: { en: "March 2024", de: "März 2024" },
    github: "https://github.com/ItO210/educational-coding-game",
  },

  {
    title: "Aire Sano",
    can: "images/projects/AireSano/AireSanoCan.webp",
    images: [
      { src: "images/projects/AireSano/1.webp", alt: "Image1" },
      { src: "images/projects/AireSano/2.webp", alt: "Image2" },
      { src: "images/projects/AireSano/3.webp", alt: "Image3" },
    ],
    description: {
      en: "AireSano is an IoT-based air quality monitoring system using an ESP32 microcontroller. It collects temperature, humidity, and air quality data, sends it to a REST API, stores it in MySQL, and displays it on a web dashboard for real-time and historical tracking.",
      de: "AireSano ist ein IoT-basiertes Luftqualitätsüberwachungssystem mit einem ESP32-Mikrocontroller. Es erfasst Temperatur-, Feuchtigkeits- und Luftqualitätsdaten, sendet sie an eine REST-API, speichert sie in MySQL und zeigt sie auf einem Web-Dashboard für Echtzeit- und historisches Tracking an.",
    },
    tech: [SiMysql, SiExpress, SiNodedotjs, SiArduino, SiHtml5, SiCss3, SiJss],
    features: {
      en: [
        "Real-time data collection from sensors.",
        "Wi-Fi transmission to a REST API.",
        "Database storage with MySQL.",
        "Web dashboard for data visualization.",
        "Historical trend analysis tools.",
      ],
      de: [
        "Echtzeit-Datenerfassung von Sensoren.",
        "Wi-Fi-Übertragung an eine REST-API.",
        "Datenbankspeicherung mit MySQL.",
        "Web-Dashboard zur Datenvisualisierung.",
        "Tools zur historischen Trendanalyse.",
      ],
    },
    date: { en: "September 2023", de: "September 2023" },
    github: "https://github.com/ItO210/air-monitoring-system/tree/main",
  },
];
